# Generated by Django 6.0 on 2026-01-09 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_customer_user_profile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
